easy_admin:
    design:
        brand_color: '#018EB2' 
        assets:
            favicon: '/favicon/favicon_adm.png'    
            js:
                - '/js/admin.js'                    
    formats:
        datetime: 'd/m/Y'  
    entities:
        Article:
            class: App\Entity\Article
            label: 'Articles'
            icon: 'pen-square'
            new:
                title: 'Nouvel article'
            edit:
                title:  'Modifier un article'    
            list:
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'new', label: 'Nouvel article' }
                    - { name: 'edit', icon: 'pencil' }          
                    - { name: 'delete', icon: 'remove' }          
                title:  'Les articles'        
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'image.image', type: 'image', label: 'Miniature', base_path: '%app.path.article_images%' }
            show:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'image.image', type: 'image', label: 'Miniature', base_path: '%app.path.article_images%' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'text', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', type_options: { config_name: 'advanced_config' }, label: 'Texte' }
                    - { property: 'image', label: 'Miniature', type: 'App\Form\ImageType' }
                    - { property: 'pdfs', label: 'Fichiers (pdf) :', type: 'collection', type_options: { entry_type: 'App\Form\PdfType' } }                            
        Image:
            class: App\Entity\Image
            label: 'Images'
            icon: 'pen-square'
            new:
                title: 'Nouvelle image'
            edit:
                title:  'Modifier une image'    
            list:
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'new', label: 'Nouvelle image' }
                    - { name: 'edit', icon: 'pencil' }          
                    - { name: 'delete', icon: 'remove' }          
                title:  'Les images'        
                fields:
                    - { property: 'alt', label: 'Description' }
                    - { property: 'image', type: 'image', label: 'Miniature', base_path: '%app.path.article_images%' }    
            show:
                fields:
                    - { property: 'alt', label: 'Description' }
                    - { property: 'image', type: 'image', label: 'Miniature', base_path: '%app.path.article_images%' }    
            form:
                fields:
                    - { property: 'alt', label: 'Description' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', type_options: { allow_delete: false } }
        Partenaire:
            class: App\Entity\Partenaire
            label: 'Partenaires'
            icon: 'pen-square'
            new:
                title: 'Nouveau partenaire'
            edit:
                title:  'Modifier un partenaire'    
            list:
                actions:
                    - { name: 'show', icon: 'search' }
                    - { name: 'new', label: 'Nouveau partenaire' }
                    - { name: 'edit', icon: 'pencil' }          
                    - { name: 'delete', icon: 'remove' }          
                title:  'Les articles'        
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'url', label: 'URL' }
                    - { property: 'image', type: 'image', label: 'Logo', base_path: '%app.path.partenaire_images%' }    
            show:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'url', label: 'URL' }
                    - { property: 'image', type: 'image', label: 'Logo', base_path: '%app.path.partenaire_images%' }    
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'url', label: 'URL' }
                    - { property: 'imageFile', type: 'vich_image', label: 'Logo', type_options: { allow_delete: false } }   
                    - { property: 'imageData', type: 'hidden', label: 'URL', type_options: { required: true }  }                                                       
    site_name: "Club d'Aviron Saintais"         