fm_elfinder:
    instances:
        default:
            editor:           "ckeditor"
            path_prefix: "/"
            connector:
                roots:
                    uploads:
                        driver:           "LocalFileSystem"
                        path: uploads/articles/Images
                        upload_allow:     ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']